version: "3"

services:

  app:
    build: .
    ports: 
      - 9000:8000
    volumes:
      - .:/app
    command: python app_project/manage.py runserver 0.0.0.0:8000

  db:
    image: postgres
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: 123456
    ports: 
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: